### ISSUE TITLE
TK19

### ISSUE THREAD

**Issue by VoidScriptz** [Scriptkia/Kia-Hub#3]
How i fix TK19 @Scriptkia? Everytime i launch appears:
//FATAL ERROR//
`TK19B isn't existent. Please use the key you got here for reporting this problem.`
`W82niw091KowEu72mzWImPmis2830`
That was my key. Help! @Scriptkia
😐•_•

**Comment by Scriptkia** [comment]
This was fixed! Thanks for reporting, @VoidScriptz! You helped alot, althought no one got so much this error and just you got it!
You fix tk19 by injecting this code (infront of kia's code)
print("data2-tk19-update")

If it appears "data2-tk19-update" in the console, it means it worked and now kia will inject!
